# Generated by Django 4.1.7 on 2023-06-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='category',
            field=models.ManyToManyField(related_name='books_cat', to='book.categories', verbose_name='Специальность'),
        ),
    ]
